# wrangler.toml
name = 'eds-teams-channel-worker'
compatibility_date = "2025-04-16"
workers_dev = true
preview_urls = false
main = "src/main.js"

[[kv_namespaces]]
binding = "TEAMS_KV"
id = "862abef7a5eb46c996ce6c4261c640c0"


[triggers]
crons = ["0 */12 * * *", "0 0 1 * *"]  # every 12 hours AND monthly on the 1st

[[queues.producers]]
queue = "team-stats-queue"
binding = "TEAM_STATS_QUEUE"

[[queues.producers]]
queue = "teams-analytics-queue"
binding = "TEAMS_ANALYTICS_QUEUE"


[[queues.consumers]]
queue = "team-stats-queue"
binding = "TEAM_STATS_QUEUE"

[[queues.consumers]]
queue = "teams-analytics-queue"
binding = "TEAMS_ANALYTICS_QUEUE"
