# wrangler.toml
name = 'eds-teams-channel-worker'
compatibility_date = "2025-04-16"
workers_dev = true
preview_urls = false
main = "src/main.js"

[[kv_namespaces]]
binding = "TEAMS_KV"
id = "87ed889948c34679b4be4d3eccbb1350"

[[queues.producers]]
binding = "TEAM_STATS_QUEUE"
queue = "team-stats-queue"

[[queues.consumers]]
queue = "team-stats-queue"

[triggers]
crons = ["0 * * * *"] # every hour at minute 0

[logs]
level = "info"

